# @package _global_
equation: 
nt: 14

datasize: 10000
initial_time_steps: 3328 # 256 * 13
num_acquire: 4 # 256 * 2^4 = 4096
ensemble_size: 2
selection_method: random
seed: 1
device: cuda
acquisition_mode: time # time, whole

train:
  unrolling: 0
  epochs: 500
  lr: 0.001
  batch_size: 32
  # batch_size: 512

wandb:
  use: True
  project: 
  entity: kaist_yegonkim

# # Choices for certain parameters
# equation_choices:
#   - KdV
#   - Burgers
#   - KS

# experiment_choices:
#   - direct_random
#   - direct_variance
#   - direct_lcmd
#   - trajectory_random
#   - trajectory_variance
#   - trajectory_lcmd

# selection_method_choices:
#   - random
#   - variance
#   - stochastic
#   - lcmd
#   - lcmd_shared

# feature_choices:
#   - direct
#   - trajectory
  