# @package _global_
equation: KdV
nt: 14

batch_acquire: 32
initial_datasize: 128
num_acquire: 12
ensemble_size: 5
selection_method: random
selection_feature: direct
num_random_pool: 1000
seed: 1
datasize: 10000
testsize: 10000
fix_initial_weights: False
device: cuda


train:
  unrolling: 0
  epochs: 100
  lr: 0.001
  batch_size: 32

wandb:
  use: True
  project: 
  entity: kaist_yegonkim

# # Choices for certain parameters
# equation_choices:
#   - KdV
#   - Burgers
#   - KS

# experiment_choices:
#   - direct_random
#   - direct_variance
#   - direct_lcmd
#   - trajectory_random
#   - trajectory_variance
#   - trajectory_lcmd

# selection_method_choices:
#   - random
#   - variance
#   - stochastic
#   - lcmd
#   - lcmd_shared

# feature_choices:
#   - direct
#   - trajectory
  