# @package _global_
defaults:
  - default_conf
equation: Burgers
train:
  unrolling: 0
wandb:
  project: Burgers

datasize: 10000
testsize: 1000

model:
  n_modes: [32]

dataset:
  train_path: /mnt/home/yegonkim/home/lupi/data_exp/Burgers_train_10000.h5
  test_path: /mnt/home/yegonkim/home/lupi/data_exp/Burgers_test_1000.h5

generate_data:
  L: 1
  nt: 200
  end_time: 2.
  nu: 0.01
  atol: 1e-9
  rtol: 1e-9
  batch_size: 1024
