# @package _global_
defaults:
  - default_conf
equation: CNS
train:
  unrolling: 0
wandb:
  project: CNS

# datasize: 1000
# testsize: 1
datasize: 10000
testsize: 1000


nt: 27

model:
  n_modes: [32, 32]

dataset:
  train_path: /mnt/home/yegonkim/home/lupi/data_exp/CNS2_train_10000.h5
  test_path: /mnt/home/yegonkim/home/lupi/data_exp/CNS2_test_1000.h5
# dataset:
#   train_path: data/NS_train_1000.h5
#   test_path: data/NS_test_1.h5


generate_data:
  nt: 50
  nt_effective: 27
  nx: 32
  L: 1
  eta: 0.005
  zeta: 0.005
  end_time: 0.5
  batch_size: 64
