# @package _global_
defaults:
  - default_conf
equation: KS
train:
  unrolling: 0
wandb:
  project: KS



datasize: 10000
testsize: 1000

model:
  n_modes: [128]

dataset:
  train_path: data_exp/KS_train_10000.h5
  test_path: data_exp/KS_test_1000.h5


generate_data:
  nt: 341
  nx: 256
  end_time: 102.0
  batch_size: 1024
