# @package _global_
defaults:
  - default_conf
equation: KS
train:
  unrolling: 0
wandb:
  project: KS

nt: 27

datasize: 10000
testsize: 1000

model:
  n_modes: [128]

dataset:
  train_path: data/KS_train_10000_short.h5
  test_path: data/KS_test_1000_short.h5


generate_data:
  nt: 241
  nx: 256
  end_time: 36.0
  batch_size: 1024
