# @package _global_
equation: 
nt: 131

datasize: 10000
testsize: 10000
# exponential_data: False
whole_initial_datasize: 0
initial_datasize: 32
num_acquire: 4
ensemble_size: 1
p: 1.0

comment: 

seed: 1
device: cuda
eval_batch_size: 256

train:
  unrolling: 0
  epochs: 100
  lr: 0.001
  batch_size: 32

wandb:
  use: True
  project: 
  entity: kaist_yegonkim
