# @package _global_
equation: 
nt: 14

datasize: 4096
ensemble_datasize: 256
testsize: 1000
# exponential_data: False
initial_datasize: 32
num_acquire: 4
ensemble_size: 1
p: 1.0

# preliminary
# prelim_datasize: [16, 32, 64, 128, 256]
prelim_datasize: [256]
# p_list: [1.0, 0.5, 0.25, 0.125]
p_list: [0.5, 0.25, 0.125]
prelim_ensemble_size: 5
threshold: 1
prelim_save: True

comment: 

seed: 1
device: cuda
eval_batch_size: 256

train:
  unrolling: 0
  epochs: 100
  lr: 0.001
  batch_size: 32


generate_data:
  L: 
  nt: 
  nx: 256
  end_time: 
  nt_effective: 140
  solver: dopri5
  batch_size: 4096
  nu: 

wandb:
  use: True
  project: 
  entity: kaist_yegonkim
