# @package _global_
equation: 
nt: 14

datasize: 1000
testsize: 10000
# exponential_data: False
whole_initial_datasize: 128
initial_datasize: 128
batch_acquire: 32
num_acquire: 4 # 128 + 32*4 = 256
ensemble_size: 1


timesteps: 13

comment: 

seed: 1
device: cuda
eval_batch_size: 256

train:
  unrolling: 0
  epochs: 100
  lr: 0.001
  batch_size: 32

wandb:
  use: True
  project: 
  entity: kaist_yegonkim
